version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn install
artifacts:
  files:
    - target/HwMvnProject-0.0.1-SNAPSHOT.war
